server:
  port: 8888

logging:
  file:
    name: mylog.log
    path: logs

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/course?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234

mybatis:
  type-aliases-package:
  mapper-locations:
    - mapper/*
